### PR TITLE
Update Tags if Duplicate Post is Found

### PR DESCRIPTION
**Pull request by gljames24**
I added a feature that will append new tags to a szurubooru post if the exact post is already found during a media upload. I don't know if you would want to make it a cli or config flag so I left it as True in the if statement.

### CODE REVIEW

**Comment by reluce** [comment]
I merged the main branch and added the cli/config option `update-tags-if-exists` for the `import-from-url` script.
While I was at it, I tried to improve some things. Could you check if everything still works as intended?

**Comment by gljames24** [comment]
I got it in a usuble spot for me and tweaked some things for my usecase, but I ended up writing a bash script to run upload-media recursively thru folders with multiple threads and it's a lot faster. I'll upload my changes to my branch, but I want to spend some time looking into a multithreading recursive folder file upload in python that would be good to have as a function in upload-media that the other scripts can call.

**Comment by gljames24** [comment]
This is in a decent state. I'm not quite satisfied with the user escape as it takes way to long to clean up the worker threads, but I added multi-threading and got the tag, source, and safety to update in upload media. The concurrent workers should probably default to 1 and have a cli arg for num threads. I also would need to add the update option to upload media and pull the file upload from imports to upload media.

**Comment by reluce** [comment]
I created another PR with our changes on #53, as it got quite confusing as you started to include the multi threading feature later on.

Creating multiple threads for each post was something I thought about as well in the past, but the problem would be that all related posts wouldn't be updated correctly if there are multiple related ones to upload. This isn't an issue with sequential uploading, but it will obviously take a toll on speed. As the functionality of this script isn't time critical and implementing multi threading would add complexity, I didn't want to dig any deeper on this.

But if the user has the choice to use multi threading, I guess it would be fine if the changes are manageable.

If you want, you can create another PR with your suggested changes, but I'll close this one for now as the feature is implemented in main now and will be out on `1.0.1`.

**Pull request closed without merging**
